Volunteering.UI/Controllers/InvitationController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Volunteering.Domain.Entities;
using Volunteering.Service;
using Volunteering.Service.Identity;

namespace Volunteering.UI.Controllers
{

    public class InvitationController : Controller
    {

        InvitationService invtService = new InvitationService();
        UserService usrService = new UserService();

        //ref Current user
        //HttpContext.User.Identity.GetUserId();


        // GET: Invitation
        public ActionResult Index()
        {


            return View(invtService.GetAll());
        }

        // GET: Invitation/Details/5
        public ActionResult Details(int id)
        {
            return View(invtService.GetById(id));
        }



        // GET: Invitation/Create
        //[HttpGet]
        [HttpPost]
        //[Route("Invitation/{idV}/{idA}")]
        public ActionResult InvitCreate(string idV, int idA)
        {
            //try
            //{
            Invitation I = new Invitation();
            InvitationService IS = new InvitationService();
            
            
            I.Status = Domain.Enums.InvitationStatus.Unanswered;
            I.ActionId = idA;
            I.VolunteerId = idV;
           if(IS.NumberOfInvitesIfExist(idA, idV) == 0)
                    invtService.Add(I);
           
                    try
                    {
                        invtService.Commit();
                    }
                    catch (System.Data.Entity.Validation.DbEntityValidationException ex)
                    {
                        foreach (var entityValidationErrors in ex.EntityValidationErrors)
                        {
                            foreach (var validationError in entityValidationErrors.ValidationErrors)
                            {
                                Response.Write("Property: " + validationError.PropertyName + " Error: " + validationError.ErrorMessage);
                            }
                        }

                        //           }
                        //           catch
                        //           {
                        //return View();
                        //           }
                    
                
            }
            return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
        }
        [HttpPost]
        public ActionResult InvitupdateA( int idI, FormCollection collection)
        {
            //try
            //{

            foreach (var item in invtService.ForUpdateInv(idI))
            {
                item.Status = Domain.Enums.InvitationStatus.Accepted;
                invtService.Update(item);

            }
            try
            {
                invtService.Commit();
            }
            catch (System.Data.Entity.Validation.DbEntityValidationException ex)
            {
                foreach (var entityValidationErrors in ex.EntityValidationErrors)
                {
                    foreach (var validationError in entityValidationErrors.ValidationErrors)
                    {
                        Response.Write("Property: " + validationError.PropertyName + " Error: " + validationError.ErrorMessage);
                    }
                }


            }


            return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
        }
        [HttpPost]
        public ActionResult InvitupdateR(int idI)
        {
            //try
            //{

            
            foreach (var item in invtService.ForUpdateInv(idI))
            {
                item.Status = Domain.Enums.InvitationStatus.Refused;
                invtService.Update(item);
                
            }
            try
            {
                invtService.Commit();
            }
            catch (System.Data.Entity.Validation.DbEntityValidationException ex)
            {
                foreach (var entityValidationErrors in ex.EntityValidationErrors)
                {
                    foreach (var validationError in entityValidationErrors.ValidationErrors)
                    {
                        Response.Write("Property: " + validationError.PropertyName + " Error: " + validationError.ErrorMessage);
                    }
                }


            }

            
            return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
        }

        public ActionResult DeleteInvit( string idV, int idA)
        {
            //try
            //{
           

            var x =  invtService.FordeleteInv(idA, idV);

            foreach (Invitation i in x)
            {
                invtService.Delete(i);
            }

            try
            {
                invtService.Commit();
            }
            catch (System.Data.Entity.Validation.DbEntityValidationException ex)
            {
                foreach (var entityValidationErrors in ex.EntityValidationErrors)
                {
                    foreach (var validationError in entityValidationErrors.ValidationErrors)
                    {
                        Response.Write("Property: " + validationError.PropertyName + " Error: " + validationError.ErrorMessage);
                    }
                }

                //           }
                //           catch
                //           {
                //return View();
                //           }
            }
            return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
        }
        // POST: Invitation/Create
        //[HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Invitation/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Invitation/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Invitation/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Invitation/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Volunteering.UI/Controllers/VoluntaryActionController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Volunteering.Domain.Entities;
using Volunteering.Domain.Enums;
using Volunteering.Service;
using Volunteering.Service.Identity;

namespace Volunteering.UI.Controllers
{
    [Authorize(Roles = "Ngo")]
    public class VoluntaryActionController : Controller
    {

        private VoluntaryActionService vas = new VoluntaryActionService();
        private  UserService us = new UserService();
        [AllowAnonymous]
        // GET: VoluntaryAction
        public ActionResult Index(string searchName , string searchAddress )
        {
            List<VoluntaryAction> actions = Session["actions"] as List<VoluntaryAction>;
            actions = vas.GetAll().ToList();
            if ((!String.IsNullOrEmpty(searchName)) || (!String.IsNullOrEmpty(searchAddress)))
            {
                actions = actions.Where(m => m.Name.Contains(searchName)).Where(o => o.Address.Contains(searchAddress))
                    .ToList();
            }
            return View(actions);




            //return View(vas.GetAll());
          
           
        }
         [AllowAnonymous]
        //[Authorize(Roles = "Ngo")]
        // GET: VoluntaryAction/Details/5
        public ActionResult Details(int id)
        {

            InvitationService I = new InvitationService();

            IEnumerable<Volunteer> Vol = I.GetInvites();
            IEnumerable<Invitation> INVITES = I.GetAllInvites();
            IEnumerable<Invitation> IA = I.GetInvitOfSelectedAction(id);
           
            foreach (var item in IA)
            {

                ViewBag.SiA = item.VolunteerId;

            }

            ViewBag.actionId = id;
            ViewBag.invitations = INVITES;
            ViewBag.VolNotInvited = Vol;
            ViewBag.VolInvited = I.VolInvited(id);
            return View(vas.GetById(id));
        }

        // GET: VoluntaryAction/Create
        //[Authorize(Roles = "Ngo")]
        
        public ActionResult Create()
        {
            return View();
        }

        // POST: VoluntaryAction/Create
        [HttpPost]
        //[Authorize(Roles = "Ngo")]
        public ActionResult Create(VoluntaryAction V)
        {
            VoluntaryAction v = new VoluntaryAction();
            //try
            //{
                v.Name = V.Name;
                v.Address = V.Address;
                v.Description = V.Description;
                v.StartDate = V.StartDate;
                v.EndDate = V.EndDate;
                v.MaxVolunteers = V.MaxVolunteers;
                v.ActionType = V.ActionType;
                 v.CreatorNgoId = User.Identity.GetUserId();
            vas.Add(v);
                vas.Commit();


                return RedirectToAction("Index");
            //}
            //catch
            //{
            //    return View();
            //}
        }

        // GET: VoluntaryAction/Edit/5
        //[Authorize(Roles = "Ngo")]
        public ActionResult Edit(int id)
        {
            return View(vas.GetById(id));
        }

        // POST: VoluntaryAction/Edit/5
        //[Authorize(Roles = "Ngo")]
        [HttpPost]
        public ActionResult Edit(int id, VoluntaryAction V)
        {
            VoluntaryAction action = new VoluntaryAction();
            action = vas.GetById(V.ActionId);

            try
            {
                action.Name = V.Name;
                action.Address = V.Address;
                action.Description = V.Description;
                action.StartDate = V.StartDate;
                action.EndDate = V.EndDate;
                action.MaxVolunteers = V.MaxVolunteers;
                action.ActionType = V.ActionType;
                vas.Commit();
                //return View();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        //[Authorize(Roles = "Ngo")]
        // GET: VoluntaryAction/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                vas.Delete(vas.GetById(id));
                vas.Commit();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // POST: VoluntaryAction/Delete/5
        [HttpPost]
        //[Authorize(Roles = "Ngo")]
        public ActionResult Delete(int id, VoluntaryAction V)
        {

                return View();
            
        }

        [AllowAnonymous]
        // GET: VoluntaryAction/ListParticipants/5
        public ActionResult ListParticipants(int id)
        {


            IEnumerable<Volunteer> participants = new List<Volunteer>();
            participants = vas.GetById(id).Participants;
            ViewBag.participants = participants;

            return View(vas.GetById(id));
        }



        // POST: VoluntaryAction/Participate
        [HttpPost]
        [AllowAnonymous]
        public ActionResult Participate(int id)
        {
            vas.Participate(id,User.Identity.GetUserId());

            return RedirectToAction("Index");
        }


        // POST: VoluntaryAction/Participate
        [HttpPost]
        [AllowAnonymous]
        public ActionResult CancelParticipation(int id)
        {

            vas.Participate(id, User.Identity.GetUserId());

            return RedirectToAction("Index");
        }

       
    }
}

Volunteering.UI/Views/VoluntaryAction/Create.cshtml
@model Volunteering.Domain.Entities.VoluntaryAction

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal well well-lg">
        <h4>VoluntaryAction</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" , id="EndDate" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2"  })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxVolunteers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxVolunteers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaxVolunteers, "", new { @class = "text-danger" })
            </div>
        </div>
        
        
        <div class="form-group">
            @Html.LabelFor(model => model.ActionType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.ActionType, "Select Action Type", new { @class = "form-control"})
                @Html.ValidationMessageFor(model => model.ActionType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyB8BtMRdu9tvtEaHDsoRFKafb3eDeiUcGA&libraries=places">

</script>
<script type="text/javascript">

            google.maps.event.addDomListener(window, 'load', function () {
                //var options = {
                //    types: ['(cities)'],
                //    componentRestrictions: { country: "tn" }
                //};
                var input = document.getElementById('Address');
                var places = new google.maps.places.Autocomplete(input);


            });
</script>  

Volunteering.UI/Views/VoluntaryAction/Details.cshtml
@using System.Activities.Statements
@using System.Web.Razor.Tokenizer
@using Microsoft.AspNet.Identity
@using Volunteering.Service
@model Volunteering.Domain.Entities.VoluntaryAction

@{
    ViewBag.Title = "Details";
}


<h2>Details</h2>

<div>
    <h4>VoluntaryAction</h4>
    <hr />
    <dl class="col-md-8 well well-lg">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaxVolunteers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxVolunteers)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ActionType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActionType)
        </dd>

        <dt>
            Organization Name
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.CreatorNgo.UserName)*@
            @Html.DisplayFor(modelItem =>
                new @VoluntaryActionService().GetNgoCreatorById(Model.CreatorNgoId).Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Participants)
        </dt>

        <dd>
            @*@Html.DisplayName(new @VoluntaryActionService().GetById(Model.ActionId).Participants.Count.ToString())*@
            @foreach (var action in new @VoluntaryActionService().GetAllActions())
            {
                if (action.ActionId==Model.ActionId)
                {
                    @Html.DisplayName(action.Participants.Count.ToString())
                }
                
               

            }
            <br /><br />
       
            @Html.ActionLink("See the list of participants", "ListParticipants", new {id = Model.ActionId})
            @if (Request.IsAuthenticated)
            {

            if (!(new VoluntaryActionService().IsParticipated(Model.ActionId, User.Identity.GetUserId())))
             {

                 using (Html.BeginForm("Participate", "VoluntaryAction", new {id = Model.ActionId}))
                 {
                     <input type="submit" value="Participate" class="btn btn-success"/>
                 }

             }
             else
             {

                 using (Html.BeginForm("Participate", "VoluntaryAction", new {id = Model.ActionId}))
                 {
                     <input type="submit" value="Cancel" class="btn btn-danger"/>
                 }
             }
        }
        </dd>

    </dl>

</div>


<div class="col-md-4 well well-lg">
    <h3>Peoples to invite</h3>

    <table>


        @foreach (var item in ViewBag.VolNotInvited)
            {


            <tr>
                <td>


                    <span> @item.Email</span>


                </td>

                <td>

                    @using (Html.BeginForm("InvitCreate", "Invitation", new { idA = @ViewBag.actionId, idV = @item.Id }, FormMethod.Post, null))

                    {


                        <input type="submit" value="Inviter" class="btn btn-success" />

                    }
                </td>

            </tr>
        }


    </table>

</div>
<div class="col-md-4 well well-lg">
    <h3>Peoples alreday invited</h3>
    <table>

        @foreach (var item in ViewBag.VolInvited)
            {
            <tr>
                <td>


                    <span> @item.Email</span>
                </td>

                <td>


                    @using (Html.BeginForm("DeleteInvit", "Invitation", new { idA = @ViewBag.actionId, idV = @item.Id }, FormMethod.Post, null))

                {
                        <input type="submit" value="Annuler l'invitation" class="btn btn-danger" onclick ="return confirm('Are you sure you want to delete the invitation ?');"/>
                    }

                </td>
            </tr>
        }
    </table>
</div>

<div>
    <p>

        @Html.ActionLink("Edit", "Edit", new { id = Model.ActionId }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</div>

Volunteering.UI/Views/VoluntaryAction/Edit.cshtml
@model Volunteering.Domain.Entities.VoluntaryAction

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal well well-lg">
        <h4>VoluntaryAction</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ActionId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxVolunteers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxVolunteers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaxVolunteers, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ActionType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.ActionType, "Select Action Type", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ActionType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyB8BtMRdu9tvtEaHDsoRFKafb3eDeiUcGA&libraries=places">
</script>
<script type="text/javascript">

    google.maps.event.addDomListener(window, 'load', function () {
        //var options = {
        //    types: ['(cities)'],
        //    componentRestrictions: { country: "tn" }
        //};
        var input = document.getElementById('Address');
        var places = new google.maps.places.Autocomplete(input);


    });
</script>  

Volunteering.UI/Views/VoluntaryAction/Index.cshtml
@using Volunteering.Service
@model IEnumerable<Volunteering.Domain.Entities.VoluntaryAction>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@using (Html.BeginForm())
{
    <table>
        <tr>
            <td>
                <div>
                    Action Name @Html.TextBox("searchName")
                    Location @Html.TextBox("searchAddress")
                </div>
               
                    
                
            </td>
            <td>
                <input type="submit" value="Search" id="submit" />
            </td>
        </tr>
    </table>
}

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div class="dl-horizontal well well-lg">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MaxVolunteers)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ActionType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatorNgo)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MaxVolunteers)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ActionType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem =>
                        new @VoluntaryActionService().GetNgoCreatorById(item.CreatorNgoId).Email)
                </td>



                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ActionId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ActionId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ActionId })
                </td>
            </tr>
        }

    </table>
</div>
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyB8BtMRdu9tvtEaHDsoRFKafb3eDeiUcGA&libraries=places">

</script>
<script type="text/javascript">

    google.maps.event.addDomListener(window, 'load', function () {
        //var options = {
        //    types: ['(cities)'],
        //    componentRestrictions: { country: "tn" }
        //};
        var input = document.getElementById('searchAddress');
        var places = new google.maps.places.Autocomplete(input);


    });
</script>  

Volunteering.UI/Views/VoluntaryAction/ListParticipants.cshtml
@model Volunteering.Domain.Entities.VoluntaryAction
@using Volunteering.Service
@{
    ViewBag.Title = "ListParticipants";
}

<h2>ListParticipants</h2>

<div>
    <h4>VoluntaryAction</h4>
    <hr />
   
       
        
        
    <table class="table">

        <tr>

            <th>
                Volunteer Name
            </th>
            <th>
                Volunteer Email
            </th>
        </tr>


        @foreach (var action in new @VoluntaryActionService().GetAllActions())
        {

            if (action.ActionId==Model.ActionId)
            {
                foreach (var item in action.Participants)
                {
                    <tr>
                        <td>
                            @item.UserName
                        </td>
                        <td>
                            @item.Email
                        </td>
                    </tr>
            }


            
            }



        }
    </table>



@*<dd>
            @Html.DisplayName(new @VoluntaryActionService().GetAllActions().Count().ToString())
            @foreach (var action in new @VoluntaryActionService().GetAllActions())
            {
                foreach (var VARIABLE in action.Participants)
                {
                    @Html.DisplayName(VARIABLE.UserName)
                }

            }
            @Html.ActionLink("See the list of participants", "Index")
        </dd>


    </dl>*@
</div>
<p>
    @Html.ActionLink("Back to Action Details", "Details", new { id = Model.ActionId })
</p>

Volunteering.UI/Views/VoluntaryAction/_Vlist.cshtml
@model IEnumerable<Volunteering.Domain.Entities.Volunteer>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>

           
        </tr>
    }

</table>