Volunteering.UI/Controllers/DonationController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Volunteering.Domain.Entities;
using Volunteering.Service;
using Volunteering.Service.Identity;

namespace Volunteering.UI.Controllers
{
    public class DonationController : Controller
    {

        //===========================//
        //--------- INIT ------------//
        //===========================//

        private readonly DonationService donService = new DonationService();


        //===========================//
        //--------- VIEW ----------  //
        //===========================//

        // GET: Donation
        public ActionResult Index()
        {
            return View(donService.GetAll());

        }

        // GET: Donation/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        //===========================//
        //--------- CREATE ----------//
        //===========================//

        // GET: Donation/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Donation/Create
        [HttpPost]
        public ActionResult Create(Donation Don)
        {
            Console.WriteLine(Don.CampaignId);
            Console.WriteLine(Don.Amount);
            return View();



            //try
            //{
            //    UserService us = new UserService();


            //    Donation don = new Donation();
            //    Volunteer volunteer = us.UserManager.FindById(System.Web.HttpContext.Current.User.Identity.GetUserId()) as Volunteer;
            //    FundraisingCampaign fund = new FundraisingCampaign();


            //    don.Amount = Don.Amount;
            //    don.Volunteer = volunteer;
            //    don.Campaign = fund;

            //    donService.Add(don);
            //    donService.Commit();




            //    return RedirectToAction("Index");
            //}
            //catch
            //{
            //    return View();
            //}
        }

        //===========================//
        //--------- Edit ------------//
        //===========================//

        // GET: Donation/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Donation/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //===========================//
        //--------- DELETE ----------//
        //===========================//

        // GET: Donation/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Donation/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //===========================//
        //--------- DONATE ----------//
        //===========================//

        // GET: Donation/Create
        public ActionResult Donate()
        {
            return View();
        }

        // POST: Donation/Create
        [HttpPost]
        public ActionResult Donate(FormCollection collection)
        {
            try
            {
                Donation don = new Donation();



                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


    }
}

Volunteering.UI/Controllers/FundraisingCampaignController.cs
using Microsoft.AspNet.Identity;
using System.Web.Mvc;
using Volunteering.Domain.Entities;
using Volunteering.Service;
using Volunteering.Service.Identity;

namespace Volunteering.UI.Controllers
{
    public class FundraisingCampaignController : Controller
    {

        //===========================//
        //--------- INIT ----------
        //===========================//

        private readonly FundraisingCampaignService fcService = new FundraisingCampaignService();
        private readonly UserService us = new UserService();



        //===========================//
        //--------- VIEW ----------
        //===========================//

        // GET: FundraisingCampaign
        public ActionResult Index()
        {

            return View(fcService.GetAll());
        }


        // GET: FundraisingCampaign/Details/5
        public ActionResult Details(int id)
        {

            return View(fcService.GetById(id));
        }

        //===========================//
        //--------- CREATE ----------
        //===========================//

        // GET: FundraisingCampaign/Create
        public ActionResult Create()
        {
            return View();
        }


        // POST: FundraisingCampaign/Create
        [HttpPost]
        [Authorize(Roles = "Ngo")]
        public ActionResult Create(FundraisingCampaign Fund)
        {            
                FundraisingCampaign fund = new FundraisingCampaign() ;
                Ngo ngo = us.UserManager.FindById(System.Web.HttpContext.Current.User.Identity.GetUserId()) as Ngo;
                fund.Name = Fund.Name;
                fund.Description = Fund.Description;
                fund.StartDate = Fund.StartDate;
                fund.EndDate = Fund.EndDate;
                fund.TargetAmount = Fund.TargetAmount;
                fund.OwnerNgoId = User.Identity.GetUserId();
                fcService.Add(fund);
                fcService.Commit();
                return RedirectToAction("Index");
           
            
        }

        //===========================//
        //---------- EDIT ----------
        //===========================//

        // GET: FundraisingCampaign/Edit/5
        public ActionResult Edit(int id)
        {
            return View(fcService.GetById(id));
        }

        // POST: FundraisingCampaign/Edit/5
        [HttpPost]
        [Authorize(Roles = "Ngo")]
        public ActionResult Edit(int id, FormCollection collection, FundraisingCampaign Fund)
        {
            try
            {
                FundraisingCampaign fundation = new FundraisingCampaign();
                fundation = fcService.GetById(Fund.CampaignId);

                fundation.Name = Fund.Name;
                fundation.Description = Fund.Description;
                fundation.StartDate = Fund.StartDate;
                fundation.EndDate = Fund.EndDate;
                fundation.TargetAmount = Fund.TargetAmount;
                fcService.Commit();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //===========================//
        //--------- DELETE ----------
        //===========================//

        // GET: FundraisingCampaign/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: FundraisingCampaign/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection, FundraisingCampaign Fund)
        {
            try
            {
                // TODO: Add delete logic here
                FundraisingCampaign test = new FundraisingCampaign();

                
                fcService.Delete(fcService.GetById(id));
                fcService.Commit();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //====================================================//
        //--------- Get FundraisingCompaign By Ngo  ----------//
        //=================================================== //

        
        // GET: FundraisingCampaign/ngoCompaigns
        public ActionResult NgoCompaigns()
        {

            return View(fcService.FundraisingCompaignByNgo());
        }






    }
}

Volunteering.UI/Views/FundraisingCampaign/Create.cshtml
@model Volunteering.Domain.Entities.FundraisingCampaign

<div class="col-md-9 well well-lg">


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>FundraisingCampaign</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TargetAmount, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TargetAmount, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TargetAmount, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
</div>

Volunteering.UI/Views/FundraisingCampaign/Delete.cshtml
@model Volunteering.Domain.Entities.FundraisingCampaign

<div class="col-md-9 well well-lg">

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>FundraisingCampaign</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.StartDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.StartDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.EndDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.EndDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TargetAmount)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TargetAmount)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
    </div>

Volunteering.UI/Views/FundraisingCampaign/Details.cshtml
@model Volunteering.Domain.Entities.FundraisingCampaign

@{
    ViewBag.Title = "Details";
}

<div class="col-md-9 well well-lg">

    <h2>Details</h2>

    <div>
        <h4>FundraisingCampaign</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.StartDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.StartDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.EndDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.EndDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TargetAmount)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TargetAmount)
            </dd>

        </dl>


        @using (Html.BeginForm("Create", "Donation", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Donation</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.Label("Amount", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBox("Amount", "", new { @class = "form-control" })

                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">

                        <input type="submit" value="Donate" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

    </div>




    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.CampaignId }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
    <br /><br /><br /><br /><br /><br />
</div>

Volunteering.UI/Views/FundraisingCampaign/Edit.cshtml
@model Volunteering.Domain.Entities.FundraisingCampaign

<div class="col-md-9 well well-lg">


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>FundraisingCampaign</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.CampaignId)

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TargetAmount, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TargetAmount, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TargetAmount, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
</div>

Volunteering.UI/Views/FundraisingCampaign/Index.cshtml
@model IEnumerable<Volunteering.Domain.Entities.FundraisingCampaign>

@{
    ViewBag.Title = "Index";
}
<div class="well well-lg" >
    <h2>Index</h2>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TargetAmount)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TargetAmount)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.CampaignId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.CampaignId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.CampaignId })
                </td>
            </tr>
        }

    </table>
    <br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
</div>

Volunteering.UI/Views/FundraisingCampaign/NgoCompaigns.cshtml
@model IEnumerable<Volunteering.Domain.Entities.FundraisingCampaign>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TargetAmount)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    if (item.OwnerNgo == User.Identity) { 
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TargetAmount)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.CampaignId }) |
            @Html.ActionLink("Details", "Details", new { id=item.CampaignId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.CampaignId })
        </td>
    </tr>
    }
}

</table>