Volunteering.UI/Controllers/DiscussionController.cs
using Microsoft.AspNet.Identity;
using System.Web.Mvc;
using Volunteering.Domain.Entities;
using Volunteering.Service;
using Volunteering.Service.Identity;

namespace Volunteering.UI.Controllers
{
    [Authorize]
    public class DiscussionController : Controller
    {
        private readonly DiscussionService ds = new DiscussionService();
        private readonly UserService us = new UserService();


        // GET: Discussion
        public ActionResult Index()
        {
            return View();
        }

        // GET: Discussion/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Discussion/Create
        [HttpGet]
        public ActionResult CreateNewDiscussion(string email)
        {
            ViewBag.email = email;

            return View();
        }

        // POST: Discussion/Create
        [HttpPost]
        public ActionResult CreateNewDiscussion(Discussion D, string Email)
        {
            Discussion d = new Discussion();

            d.Title = D.Title;
            d.Content = D.Content;
            d.SenderId = User.Identity.GetUserId();
            if (us.UserManager.FindByEmail(Email) != null)
            {
                d.RecipientId = us.UserManager.FindByEmail(Email).Id;
            }
            else
            {
                return View();
            }


            ds.Add(d);
            ds.Commit();

            return View();

        }

        // GET: Discussion/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Discussion/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Discussion/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Discussion/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Volunteering.UI/Views/Discussion/CreateNewDiscussion.cshtml
@using Volunteering.UI.Controllers
@model Volunteering.Domain.Entities.Discussion

<div class="well well-lg">
@{
    ViewBag.Title = "CreateNewDiscussion";
}

<h2>CreateNewDiscussion</h2>

@using (Html.BeginForm("CreateNewDiscussion", "Discussion", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Discussion</h4>
        <hr />

        <!-- TITLE -->

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>


        <!-- CONTENT -->
        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Send To ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("Email" , (String)ViewBag.email)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Send" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
</div>