Volunteering.UI/Controllers/FundraisingCampaignController.cs
using Microsoft.AspNet.Identity;
using System.Web.Mvc;
using Volunteering.Domain.Entities;
using Volunteering.Service;
using Volunteering.Service.Identity;

namespace Volunteering.UI.Controllers
{
    public class FundraisingCampaignController : Controller
    {

        //===========================//
        //--------- INIT ----------
        //===========================//

        private readonly FundraisingCampaignService fcService = new FundraisingCampaignService();
        private readonly UserService us = new UserService();



        //===========================//
        //--------- VIEW ----------
        //===========================//

        // GET: FundraisingCampaign
        public ActionResult Index()
        {

            return View(fcService.GetAll());
        }


        // GET: FundraisingCampaign/Details/5
        public ActionResult Details(int id)
        {

            return View(fcService.GetById(id));
        }

        //===========================//
        //--------- CREATE ----------
        //===========================//

        // GET: FundraisingCampaign/Create
        public ActionResult Create()
        {
            return View();
        }


        // POST: FundraisingCampaign/Create
        [HttpPost]
        [Authorize(Roles = "Ngo")]
        public ActionResult Create(FundraisingCampaign Fund)
        {            
                FundraisingCampaign fund = new FundraisingCampaign() ;
                Ngo ngo = us.UserManager.FindById(System.Web.HttpContext.Current.User.Identity.GetUserId()) as Ngo;
                fund.Name = Fund.Name;
                fund.Description = Fund.Description;
                fund.StartDate = Fund.StartDate;
                fund.EndDate = Fund.EndDate;
                fund.TargetAmount = Fund.TargetAmount;
                fund.OwnerNgoId = User.Identity.GetUserId();
                fcService.Add(fund);
                fcService.Commit();
                return RedirectToAction("Index");
           
            
        }

        //===========================//
        //---------- EDIT ----------
        //===========================//

        // GET: FundraisingCampaign/Edit/5
        public ActionResult Edit(int id)
        {
            return View(fcService.GetById(id));
        }

        // POST: FundraisingCampaign/Edit/5
        [HttpPost]
        [Authorize(Roles = "Ngo")]
        public ActionResult Edit(int id, FormCollection collection, FundraisingCampaign Fund)
        {
            try
            {
                FundraisingCampaign fundation = new FundraisingCampaign();
                fundation = fcService.GetById(Fund.CampaignId);

                fundation.Name = Fund.Name;
                fundation.Description = Fund.Description;
                fundation.StartDate = Fund.StartDate;
                fundation.EndDate = Fund.EndDate;
                fundation.TargetAmount = Fund.TargetAmount;
                fcService.Commit();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //===========================//
        //--------- DELETE ----------
        //===========================//

        // GET: FundraisingCampaign/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: FundraisingCampaign/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection, FundraisingCampaign Fund)
        {
            try
            {
                // TODO: Add delete logic here
                FundraisingCampaign test = new FundraisingCampaign();

                
                fcService.Delete(fcService.GetById(id));
                fcService.Commit();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //====================================================//
        //--------- Get FundraisingCompaign By Ngo  ----------//
        //=================================================== //

        
        // GET: FundraisingCampaign/ngoCompaigns
        public ActionResult NgoCompaigns()
        {

            return View(fcService.FundraisingCompaignByNgo());
        }






    }
}

Volunteering.UI/Controllers/VoluntaryActionController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Volunteering.Domain.Entities;
using Volunteering.Domain.Enums;
using Volunteering.Service;
using Volunteering.Service.Identity;

namespace Volunteering.UI.Controllers
{
    [Authorize(Roles = "Ngo")]
    public class VoluntaryActionController : Controller
    {

        private VoluntaryActionService vas = new VoluntaryActionService();
        private  UserService us = new UserService();
        [AllowAnonymous]
        // GET: VoluntaryAction
        public ActionResult Index(string searchName , string searchAddress )
        {
            List<VoluntaryAction> actions = Session["actions"] as List<VoluntaryAction>;
            actions = vas.GetAll().ToList();
            if ((!String.IsNullOrEmpty(searchName)) || (!String.IsNullOrEmpty(searchAddress)))
            {
                actions = actions.Where(m => m.Name.Contains(searchName)).Where(o => o.Address.Contains(searchAddress))
                    .ToList();
            }
            return View(actions);




            //return View(vas.GetAll());
          
           
        }
         [AllowAnonymous]
        //[Authorize(Roles = "Ngo")]
        // GET: VoluntaryAction/Details/5
        public ActionResult Details(int id)
        {

            InvitationService I = new InvitationService();

            IEnumerable<Volunteer> Vol = I.GetInvites();
            IEnumerable<Invitation> INVITES = I.GetAllInvites();
            IEnumerable<Invitation> IA = I.GetInvitOfSelectedAction(id);
           
            foreach (var item in IA)
            {

                ViewBag.SiA = item.VolunteerId;

            }

            ViewBag.actionId = id;
            ViewBag.invitations = INVITES;
            ViewBag.VolNotInvited = Vol;
            ViewBag.VolInvited = I.VolInvited(id);
            return View(vas.GetById(id));
        }

        // GET: VoluntaryAction/Create
        //[Authorize(Roles = "Ngo")]
        
        public ActionResult Create()
        {
            return View();
        }

        // POST: VoluntaryAction/Create
        [HttpPost]
        //[Authorize(Roles = "Ngo")]
        public ActionResult Create(VoluntaryAction V)
        {
            VoluntaryAction v = new VoluntaryAction();
            //try
            //{
                v.Name = V.Name;
                v.Address = V.Address;
                v.Description = V.Description;
                v.StartDate = V.StartDate;
                v.EndDate = V.EndDate;
                v.MaxVolunteers = V.MaxVolunteers;
                v.ActionType = V.ActionType;
                 v.CreatorNgoId = User.Identity.GetUserId();
            vas.Add(v);
                vas.Commit();


                return RedirectToAction("Index");
            //}
            //catch
            //{
            //    return View();
            //}
        }

        // GET: VoluntaryAction/Edit/5
        //[Authorize(Roles = "Ngo")]
        public ActionResult Edit(int id)
        {
            return View(vas.GetById(id));
        }

        // POST: VoluntaryAction/Edit/5
        //[Authorize(Roles = "Ngo")]
        [HttpPost]
        public ActionResult Edit(int id, VoluntaryAction V)
        {
            VoluntaryAction action = new VoluntaryAction();
            action = vas.GetById(V.ActionId);

            try
            {
                action.Name = V.Name;
                action.Address = V.Address;
                action.Description = V.Description;
                action.StartDate = V.StartDate;
                action.EndDate = V.EndDate;
                action.MaxVolunteers = V.MaxVolunteers;
                action.ActionType = V.ActionType;
                vas.Commit();
                //return View();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        //[Authorize(Roles = "Ngo")]
        // GET: VoluntaryAction/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                vas.Delete(vas.GetById(id));
                vas.Commit();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // POST: VoluntaryAction/Delete/5
        [HttpPost]
        //[Authorize(Roles = "Ngo")]
        public ActionResult Delete(int id, VoluntaryAction V)
        {

                return View();
            
        }

        [AllowAnonymous]
        // GET: VoluntaryAction/ListParticipants/5
        public ActionResult ListParticipants(int id)
        {


            IEnumerable<Volunteer> participants = new List<Volunteer>();
            participants = vas.GetById(id).Participants;
            ViewBag.participants = participants;

            return View(vas.GetById(id));
        }



        // POST: VoluntaryAction/Participate
        [HttpPost]
        [AllowAnonymous]
        public ActionResult Participate(int id)
        {
            vas.Participate(id,User.Identity.GetUserId());

            return RedirectToAction("Index");
        }


        // POST: VoluntaryAction/Participate
        [HttpPost]
        [AllowAnonymous]
        public ActionResult CancelParticipation(int id)
        {

            vas.Participate(id, User.Identity.GetUserId());

            return RedirectToAction("Index");
        }

       
    }
}

Volunteering.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Volunteering Platform</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <meta name="description" content="The description of my page" />
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Volunteering", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

        </div>

        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Actions", "Index", "VoluntaryAction")</li>
                <li>@Html.ActionLink("Campaigns", "Index", "FundraisingCampaign")</li>
            </ul>

            @Html.Partial("_LoginPartial")
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
            </ul>
        </div>
    </div>
</div>

<div class="container body-content">
    <div class="panel panel-primary"></div>
    @RenderBody()
    <hr/>

</div>
<div >
    <br/>
    <br />
    <br />
    <br />
    <br />

</div>

<div class="footer">
    <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>

</div>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
@RenderSection("scripts", required: false)
</body>

</html>

Volunteering.UI/Views/Shared/_Slider.cshtml
<div class="well well-lg">
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox" style=" width:100%; height: 350px !important;">
        <div class="item active">
            <img src="https://www.w3schools.com/bootstrap/la.jpg" alt="Los Angeles">
        </div>

        <div class="item">
            <img src="https://www.w3schools.com/bootstrap/chicago.jpg" alt="Chicago">
        </div>

        <div class="item">
            <img src="https://www.w3schools.com/bootstrap/ny.jpg" alt="New York">
        </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
</div>